version: "3.7"
services:
  app:
    image: registry.danova.id/new-pmb-development/pmb-ummat/apppmb:0.0.10-ldap
    volumes:
      - ./:/var/www/html
    networks:
      - pmbummat

  db:
    image: registry.danova.id/new-pmb-development/pmb-ummat/dbpmb:0.0.3
    volumes:
      - databasevol:/var/lib/mysql
    container_name: dbpmb
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - pmbummat

  nginx:
    image: registry.danova.id/new-pmb-development/pmb-ummat/nginxpmb:0.0.8-ldap
    working_dir: /var/www/html
    container_name: nginxpmb
    # user: "1000:1000"
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    networks:
      - pmbummat

networks:
  pmbummat:
    driver: bridge

volumes:
  databasevol:
  datasave:
  appvolume:
  webvolume:
    #   driver_opts:
    #     type: none
    #     device: ${PWD}
    #     o: bind
    # databasevol:
    #   driver_opts:
    #     type: none
    #     device: ${PWD}/docker-compose/mysql
    #     o: bind
    # datasave:

    # storage/app/public/mahasiswa/gelombang20221/umum1/test123456789123456721/KTPtest21103SdHGVc3.jpg
